apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-ml-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spam
  template:
    metadata:
      labels:
        app: spam
    spec:
      containers:
      - name: spam-api
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000
